services:
  streamlit:
    build: .
    image: beeek18/streamlit-app:1.0.0
    restart: unless-stopped
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - shared-streamlit-bot-network

networks:
  shared-streamlit-bot-network:
    external: true